name: Build Backports
on:
  workflow_dispatch:

jobs:
  create_tar:
    name: Create backports tar
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install coccinelle
        run: |
          sudo apt update
          sudo apt install -y coccinelle

      - name: Checkout backports
        uses: actions/checkout@v4
        with:
          path: backports

      - name: Checkout kernel 7.0
        uses: actions/checkout@v4
        with:
          repository: mj22226/linux
          ref: refs/heads/linux-7.0
          path: linux
      - name: kernel version
        working-directory: linux
        run: |
             echo "VERSION=$(awk '/^VERSION =/{a=$3};/^PATCHLEVEL =/{b=$3};/^SUBLEVEL =/{c=$3};END{print a"."b"."c}' Makefile)" >> $GITHUB_ENV
             echo "VERSIONEX=$(awk '/^VERSION =/{a=$3};/^PATCHLEVEL =/{b=$3};/^SUBLEVEL =/{c=$3};/^EXTRAVERSION =/{d=$3};END{print a"."b"."c d}' Makefile)" >> $GITHUB_ENV
      - name: Generate backports tar
        working-directory: backports
        run: |
             ./gentree.py --refresh  ${GITHUB_WORKSPACE}/linux ${GITHUB_WORKSPACE}/backports-${{ env.VERSION }}
             echo "TAG=$(git branch | tail -c 6)" >> $GITHUB_ENV
      - name: Check for git changes
        working-directory: backports
        run: git diff
      - name: backports version
        working-directory: backports-${{ env.VERSION }}
        run: |
             sed -i '1s/="/="${{ env.TAG }}-/' versions
             sed -i '2s/="/="v${{ env.VERSIONEX }}-/' versions
      - name: Pack backports
        run: |
             tar -c backports-${{ env.VERSION }} | xz > backports-${{ env.VERSION }}.tar.xz
             sha256sum backports-${{ env.VERSION }}.tar.xz > sha256sum
             echo "HASH=$(git log -1 --format="%H")" >> $GITHUB_ENV
      - name: Release build artifacts
        uses: ncipollo/release-action@v1.14.0
        with:
          commit: ${{ env.HASH }}
          allowUpdates: true
          prerelease: false
          name: backports v${{ env.VERSIONEX }}
          tag: v${{ env.VERSIONEX }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
                    backports-${{ env.VERSION }}.tar.xz
                    sha256sum



